### ISSUE TITLE
Memory leak in single page applications

### ISSUE THREAD

**Issue by Robinfr** [alexanderdickson/waitForImages#57]
This plugin will leak memory in single page applications since there is no way to explicitly unbind the events.

**Use case:**
User loads a page, images start loading, yet switches the page before all images are done loading. Since this is a single page application, the DOM elements are removed. However, since jQuery keeps a reference to the element when there is an event handler, you now have a memory leak.

**Solution:**
Provide a function to remove the events. So any memory leaks can be avoided! :smile:

**Comment by alexanderdickson** [comment]
Are you sure it leaks memory?

To my understanding, because I listen to `load` and `error`, on a _new_ reference on an image (via `new Image()`), I should *always* get one of the callbacks, in which case there is an `off()` on the image.

Unless this happens in the selector, which only required that workaround for an old version of Firefox in 2011. It can probably be removed now.

Please let me know and I will make the change if required.

**Comment by Robinfr** [comment]
Ah, I read the source code wrong, I thought you were attaching events to the actual DOM object. But you're creating a new ``Image`` object instead. In that case I'm not sure if it matters too much. 

But, this still means that it's waiting for images to be loaded, even though the DOM objects containing those images may have already been removed. And currently, there is no way to stop these event handlers from existing (except for waiting until the images have finally been loaded).

So I suppose it would more of an optimization then a memory leak fix.

**Comment by alexanderdickson** [comment]
I can potentially check before notifying the callbacks if the containing element has been removed from the DOM.

Probably also worth removing that long-winded selector check.

I can make these changes in the next few days.
