### ISSUE TITLE
$(myImageEl).waitForImages() doesn't work

### ISSUE THREAD

**Issue by andrejpavlovic** [alexanderdickson/waitForImages#73]
It looks like the library works only elements that are children of the selector. Any particular reason? In my case, I prefer waiting only on specific images, so rather than specifying a container, the selector points directly to the image. Unfortunately, waitForImages doesn't find the src in that case..

``` javascript
// doesn't work
$('<img src="..." />')
    .appendTo('body')
    .waitForImages()
    .then(function() {
        console.log('executed immediately, because image not detected');
    });
```

**Comment by alexanderdickson** [comment]
It should do, as it has...

    obj.find('*').addBack()

[Source](https://github.com/alexanderdickson/waitForImages/blob/master/src/jquery.waitforimages.js#L106)

Are you able to step through the code and examine the jQuery collection before and after that call and confirm that it isn't being added?

**Comment by andrejpavlovic** [comment]
Hmm, but addBack() is called only if "waitForAll" is specified.

**Comment by alexanderdickson** [comment]
You're right, I missed that.

The whole idea of this plugin isn't for waiting for singular images to load by reference, but by descendent images.

In your case you could just look at the `load` event and handle it that way. Depending on how your page is setup you could use the ancestor if any other images are present and loaded they won't be *waited* for again. Alternatively the `waitForAll: true` would work because it's clear this image doesn't have a background image of its own (at least it's probable).

**Comment by andrejpavlovic** [comment]
waitForAll would work, but it's more of a workaround I guess. Ideally an edge case like this would be handled just like other cases. Adding something like this would do the trick I think:

```javascript
obj.find('img:has-src').addBack('img:has-src')
```
https://github.com/alexanderdickson/waitForImages/blob/master/src/jquery.waitforimages.js#L155

**Comment by alexanderdickson** [comment]
I will close as outside the functionality of this plugin.
